In [1]:
import pandas as pd
import numpy as np

In [ ]:
# Importamos un dataset de los precios de las casas en Boston
from sklearn import datasets ## imports datasets from scikit-learn
data = datasets.load_boston() ## loads Boston dataset from datasets library

In [3]:
# define the data/predictors as the pre-set feature names  
df = pd.DataFrame(data.data, columns=data.feature_names)

# Put the target (housing value -- MEDV) in another DataFrame
target = pd.DataFrame(data.target, columns=["MEDV"])

'''Muestra las primeras filas del dataframe df y target'''

In [4]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [5]:
X = df.to_numpy()

In [6]:
y = target.to_numpy()

In [ ]:
''' Crea un modelo de regresión lineal y entrénalo '''


In [13]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [14]:
''' Prueba a entrenarlo con df y target en lugar de X e y '''
model.fit(df,target)

LinearRegression()

In [23]:
''' Predice el precio de una vivienda con los siguintes datos
0.03731	0.0	7.07	0.0	0.469	6.421	23.5	4.9671	2.0	242.0	17.8	396.90 9.14
NOTA: se corresponde con la segunda vivienda, pero con la edad de 23.5 años en lugar de 78.9'''

X_test = np.array([[0.03731,	0.0,	7.07,	0.0,	0.469,	6.421,	23.5,	4.9671,	2.0,242.0,	17.8,	396.90, 9.14]])
X_test.shape


(1, 13)

In [24]:
model.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([[24.98613302]])

In [25]:
''' Cuál es el coeficiente de determinación R2? '''
from sklearn import metrics
y_pred = model.predict(X)
print('R2:', metrics.r2_score(y,y_pred))
print('MSE:', metrics.mean_squared_error(y,y_pred))

R2: 0.7406426641094095
MSE: 21.894831181729202


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


In [26]:
''' Muestra los coeficientes y el punto de corte (intercept) '''
model.coef_

array([[-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,
         2.68673382e+00, -1.77666112e+01,  3.80986521e+00,
         6.92224640e-04, -1.47556685e+00,  3.06049479e-01,
        -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
        -5.24758378e-01]])

In [28]:
model.intercept_

array([36.45948839])