In [81]:
import numpy as np

a = np.array([[10,2],[30,4],[60,7]])

In [82]:
print(a)
print(a[2,:])
print(a[1,1])

[[10  2]
 [30  4]
 [60  7]]
[60  7]
4


In [83]:
a = np.array([[10,2,9.4],[30,4,1.6],[60,7,8.2]])

In [84]:
a[:,[1,2]]

array([[2. , 9.4],
       [4. , 1.6],
       [7. , 8.2]])

In [85]:
a[[1,2],:]

array([[30. ,  4. ,  1.6],
       [60. ,  7. ,  8.2]])

In [86]:
np.multiply(a,2)

array([[ 20. ,   4. ,  18.8],
       [ 60. ,   8. ,   3.2],
       [120. ,  14. ,  16.4]])

In [87]:
b = np.array([[2,3],[5,7],[11,13]])
a = np.array([[10,2],[30,4],[60,7]])

#d = np.matmul(a,b) -> a@b
#c = np.multiply(a*b)


In [88]:
np.add(b,5)

array([[ 7,  8],
       [10, 12],
       [16, 18]])

In [89]:
np.power(b,3)

array([[   8,   27],
       [ 125,  343],
       [1331, 2197]])

In [90]:
np.divide(b,20)

array([[0.1 , 0.15],
       [0.25, 0.35],
       [0.55, 0.65]])

In [91]:
print((a*3+7)**2/9)
a2 = np.divide(np.power(np.add(np.multiply(a,3),7),2),9)
print(a2)

[[ 152.11111111   18.77777778]
 [1045.44444444   40.11111111]
 [3885.44444444   87.11111111]]
[[ 152.11111111   18.77777778]
 [1045.44444444   40.11111111]
 [3885.44444444   87.11111111]]


In [92]:
a=np.array([10,20,30,40,50])
f=lambda x: x+5
np.array([f(x) for x in a])

array([15, 25, 35, 45, 55])

In [93]:
a = np.array([[1,2,3],[10,20,30],[100,200,300]])
a= np.append(a,[[1000,2000,3000]], axis =0)
a = np.append(a,[[4],[40],[400],[4000]], axis = 1)

In [95]:
print(a)

[[   1    2    3    4]
 [  10   20   30   40]
 [ 100  200  300  400]
 [1000 2000 3000 4000]]
