# MATRICES

![Arrays](./arrays.png)

Mostrar una matriz por pantalla:

$ \begin{pmatrix} 1 & 2 \\ 3 & 4 \\ \end{pmatrix} $


$ \begin{pmatrix} 1 & 11 \\ 2 & 22\\ 3 & 33\\ \end{pmatrix} $


$$
\left(
\begin{pmatrix}
1 & 11\\
2 & 22\\
3 & 33
\end{pmatrix}
\begin{pmatrix}
4 & 44\\
5 & 55\\
6 & 66
\end{pmatrix}
\right)
$$


$$
\left(
\begin{array}{ll}
123 & 4 \\
1   & 234 \\
\end{array}
\right)
$$

<!---
$$
\left\{
\begin{array}{ll}
123 & 4  \\
1   & 234 
\end{array}
\right.
$$

$$
        \begin{matrix}
        1 & x & x^2 \\
        1 & y & y^2 \\
        1 & z & z^2 \\
        \end{matrix}
$$


$ \begin{matrix} 1 & 2 \\ 3 & 4 \\ \end{matrix} $
$ \begin{pmatrix} 1 & 2 \\ 3 & 4 \\ \end{pmatrix} $
$ \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ \end{bmatrix} $
$ \begin{Bmatrix} 1 & 2 \\ 3 & 4 \\ \end{Bmatrix} $
$ \begin{vmatrix} 1 & 2 \\ 3 & 4 \\ \end{vmatrix} $
$ \begin{Vmatrix} 1 & 2 \\ 3 & 4 \\ \end{Vmatrix} $

-->

$$
        \begin{pmatrix}
        1 & a_1 & a_1^2 & \cdots & a_1^n \\
        1 & a_2 & a_2^2 & \cdots & a_2^n \\
        \vdots & \vdots & \vdots & \ddots & \vdots \\
        1 & a_m & a_m^2 & \cdots & a_m^n \\
        \end{pmatrix}
$$

# EJERCICIOS

## 1

Usando la función **arange** de numpy crea un array con los números del 100 al 200 pero sin incluir el 200. Muestra el resultado.

In [242]:
import numpy as np

array = np.arange(100,200)
print (array)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]


## 2

Crea una array de numpy con los siguiente números primos: 2, 3, 5, 7, 11, 13, 17, 19, 23, 29

In [243]:
array2 = np.arange(1,30)
array2primos = []

for n in array2:
    check = True
    for i in range(1,n):
        if i == 1:
            pass
        elif n%i == 0:
            check = False
            break
    if check == True:
        array2primos = np.append(array2primos,n)
array2primos = np.delete(array2primos,0, axis = 0)
print(array2primos)

[ 2.  3.  5.  7. 11. 13. 17. 19. 23. 29.]


* Muestra el último elemento. Y debes hacerlo sin saber su longitud.

In [244]:
print(array2primos[-1])

29.0


* Muestra el 3º elemento

In [245]:
print(array2primos[2])

5.0


* Muestra el último y 3º elemento.

In [246]:
print(array2primos[2],array2primos[-1])

5.0 29.0


* Muestra del 2º al 5º elemento. 

In [247]:
print(array2primos[1:7])

[ 3.  5.  7. 11. 13. 17.]


* Muestra el 2º y el 5º elemento. 

In [248]:
print(array2primos[1],array2primos[6])

3.0 17.0


* Muestra el último y el penúltimo elemento. Y debes hacerlo sin saber su longitud. 

In [249]:
print(array2primos[-2:])

[23. 29.]


## 3

Crea la siguiente matriz:

$ \begin{pmatrix} 1 & 4 & 6 & 5 \\ 4 & 1 & 7 & 3 \\ 2 & 9 & 1 & 2 \\ 6 & 3 & 1 & 1 \\ \end{pmatrix} $


*    Muestra el elemento de la fila 2º y la columna 3º. Es el valor del 7.
*    Muestra la 3º Fila
*    Muestra la 2º Columna
*    Muestra la 2º y 3º Columna
*    Muestra la 2º y 3º Fila
*    Muestra la última columna. Debe funcionar independientemente del número de columnas.
*    Muestra la 2º y 3º Columna y la 1º y 3º fila
*    Muestra de la 2º a la 3º Columna y de la 1º a la 3º fila
*    Muestra todas las columnas excepto la primera y la última. Debe funcionar independientemente del número de columnas.
*    Muestra todas las filas excepto la primera y la última. Debe funcionar independientemente del número de filas.
*    Muestra todas las columnas excepto la primera y la última y todas las filas excepto la primera y la última. Debe funcionar independientemente del número de filas y columnas.

In [250]:
array3 = np.array([[1,4,6,5],[4,1,7,3],[2,9,1,2],[6,3,1,1]])
array3

array([[1, 4, 6, 5],
       [4, 1, 7, 3],
       [2, 9, 1, 2],
       [6, 3, 1, 1]])

* Muestra el elemento de la fila 2º y la columna 3º. Es el valor del 7.

In [251]:
print(array3[1][2])

7


* Muestra la 3º Fila

In [252]:
print(array3[2])

[2 9 1 2]


* Muestra la 2º Columna

In [253]:
print(array3[:,1])

[4 1 9 3]


* Muestra la 2º y 3º Columna

In [254]:
print(array3[:,[1,2]])

[[4 6]
 [1 7]
 [9 1]
 [3 1]]


* Muestra la 2º y 3º Fila

In [255]:
print(array3[[1,2],:])

[[4 1 7 3]
 [2 9 1 2]]


*    Muestra la última columna. Debe funcionar independientemente del número de columnas.

In [256]:
print(array3[:,-1])

[5 3 2 1]


*    Muestra la 2º y 3º Columna y la 1º y 3º fila

In [257]:
print(array3[:,[1,2]])
print(array3[[0,2],:])

[[4 6]
 [1 7]
 [9 1]
 [3 1]]
[[1 4 6 5]
 [2 9 1 2]]


*  Muestra de la 2º a la 3º Columna y de la 1º a la 3º fila

In [258]:
print(array3[0:3,[1,2]])

[[4 6]
 [1 7]
 [9 1]]


* Muestra todas las columnas excepto la primera y la última. Debe funcionar independientemente del número de columnas.

In [259]:
print(array3[:,1:-1])

[[4 6]
 [1 7]
 [9 1]
 [3 1]]


* Muestra todas las filas excepto la primera y la última. Debe funcionar independientemente del número de filas.

In [260]:
print(array3[1:-1,:])

[[4 1 7 3]
 [2 9 1 2]]


* Muestra todas las columnas excepto la primera y la última y todas las filas excepto la primera y la última. Debe funcionar independientemente del número de filas y columnas.

In [261]:

print(array3[1:-1,1:-1])

[[1 7]
 [9 1]]


## 4



El siguiente array contiene las temperaturas medias que ha hecho en Valencia en cada mes [10.2, 10.7, 13.3, 15.8, 19.3, 23.6, 26, 25.9, 22.8, 19.1, 13.9, 10.8 ]

*    Muestra las temperaturas cuyo valor sea mayor que 20
*    Muestra las temperaturas cuyo valor sea menor que 11
*    Muestra las temperaturas cuyo valor sea mayor que 20 o menor que 11



In [262]:
array4 = np.array([10.2, 10.7, 13.3, 15.8, 19.3, 23.6, 26, 25.9, 22.8, 19.1, 13.9, 10.8 ])
arr4num = np.array([])
for num in array4:
    if num > 20:
        arr4num = np.append(arr4num, num)
arr4num.sort()
print(arr4num)

[22.8 23.6 25.9 26. ]


In [263]:
arr4num = np.array([])
for num in array4:
    if num < 11:
        arr4num = np.append(arr4num, num)
arr4num.sort()
print(arr4num)

[10.2 10.7 10.8]


In [264]:
arr4num = np.array([])
for num in array4:
    if num > 11 and num < 20:
        arr4num = np.append(arr4num, num)
arr4num.sort()
print(arr4num)

[13.3 13.9 15.8 19.1 19.3]


## 5

**Matrices en 2 D**

Selecciona las celdas en rojo oscuro de la siguiente matriz:
(Crea un "muro" (matriz) de ceros y pon a 1 las celdas del centro ;-))

![muro](./muro1.png)

In [265]:
muro = np.zeros([7,8])
centro = np.ones([3,4],int)
x = 2
y = 2
muro[x:x+centro.shape[0], y:y+centro.shape[1]] = centro
muro

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

## 6

**Matrices en 3 D**

Ahora selecciona las celdas en rojo oscuro pero también las verdes y azules que hay por detrás de las rojo oscuro.
(Crea un "muro" (matriz) de ceros (de 3 dimensiones) y pon a 1 las celdas del centro en todas las dimensiones ;-))

![muro](./muro2.png)

In [266]:
muro = np.zeros([3,7,8])
centro = np.ones([3,3,4])
x = 0
y = 2
z = 2
muro[x:x+centro.shape[0], y:y+centro.shape[1], z:z+centro.shape[2]] = centro
muro

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 1., 1., 0., 0.],
        [0., 0., 1., 1., 1., 1., 0., 0.],
        [0., 0., 1., 1., 1., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 1., 1., 0., 0.],
        [0., 0., 1., 1., 1., 1., 0., 0.],
        [0., 0., 1., 1., 1., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 1., 1., 0., 0.],
        [0., 0., 1., 1., 1., 1., 0., 0.],
        [0., 0., 1., 1., 1., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

## 7

Crea la siguiente matriz:

$ \begin{pmatrix} 1 & 4 & 6 & 5 \\ 4 & 1 & 7 & 3 \\ 2 & 9 & 1 & 2 \\ 6 & 3 & 1 & 1 \\ \end{pmatrix} $


*   A todos los elementos de la matriz sumale un 10. Usando las funciones de numpy
*   A todos los elementos de la matriz sumale un 10 y divídelos entre 2. Usando las funciones de numpy
*   A todos los elementos de la matriz sumale un 10. Usando operadores
*   A todos los elementos de la matriz sumale un 10 y divídelos entre 2. Usando operadores


In [267]:
array7 = np.array([[1,4,6,5],[4,1,7,3],[2,9,1,2],[6,3,1,1]])
array7= np.add(array7,10)
array7

array([[11, 14, 16, 15],
       [14, 11, 17, 13],
       [12, 19, 11, 12],
       [16, 13, 11, 11]])

In [268]:
array7 = np.array([[1,4,6,5],[4,1,7,3],[2,9,1,2],[6,3,1,1]])
array7= np.divide(np.add(array7,10),2)
array7

array([[5.5, 7. , 8. , 7.5],
       [7. , 5.5, 8.5, 6.5],
       [6. , 9.5, 5.5, 6. ],
       [8. , 6.5, 5.5, 5.5]])

In [269]:
array7 = np.array([[1,4,6,5],[4,1,7,3],[2,9,1,2],[6,3,1,1]])
array7= array7+10
array7

array([[11, 14, 16, 15],
       [14, 11, 17, 13],
       [12, 19, 11, 12],
       [16, 13, 11, 11]])

In [270]:
array7 = np.array([[1,4,6,5],[4,1,7,3],[2,9,1,2],[6,3,1,1]])
array7= (array7+10)/2
array7

array([[5.5, 7. , 8. , 7.5],
       [7. , 5.5, 8.5, 6.5],
       [6. , 9.5, 5.5, 6. ],
       [8. , 6.5, 5.5, 5.5]])

## 8

Crea la siguiente matriz:

$ \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \\ \end{pmatrix} $

Multiplica cada elemento de la matriz por si mismo.
Multiplica la matriz por si misma.

In [271]:

array8 = np.arange(1,10,1)
array8 = array8.reshape(3,3)
array8 = np.multiply(array8,array8)
array8

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

## 9

Crea la siguiente matriz:

$ \begin{pmatrix} 1 & 0 & 0 & 0 \\ 0 & 1 & 7 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 1 \\ \end{pmatrix} $

* Obtén el elemento de la fila 2º y la columna 3º. (Es el valor del 7).
* Crea un nuevo array con los elementos de la 3º Fila de la matriz.
* Crea un nuevo array con los elementos de la 2º Columna de la matriz.
* Imprime la matriz y haz que las cabeceras de cada columna sean A, B , C y D.

In [272]:
array9 = np.identity(4)
array9[1][2] = 7
array9[1][2]

7.0

In [273]:
newarr9 = array9[2]
newarr9

array([0., 0., 1., 0.])

In [274]:
newarr9_2 = array9[:,1]
newarr9_2

array([0., 1., 0., 0.])

In [275]:
letras = ['A','B','C','D']

i = 0
for i in range(0,len(array9[0])):
    print (str(i+1).rjust(5),sep="",end="")
print()
for fila in array9:
    i+=1
    for punt in fila:
        print (str(punt).rjust(5),sep="",end="")
            
    print("\n")


    1    2    3    4
  1.0  0.0  0.0  0.0

  0.0  1.0  7.0  0.0

  0.0  0.0  1.0  0.0

  0.0  0.0  0.0  1.0



## 10

Crea una función llamada f que acepte como parámetro el número y que retorne el valor multiplicado por 2 y además que se le sume 1.

Crea ahora el vector de numpy [1,5,4,7,3,9,8,6] y aplícale la función f


In [276]:
def f(num):
    return np.add(np.multiply(num,2),1)


In [277]:
array10 = np.array([[1,5,4,7,9,8,6]])

In [278]:
f(array10)

array([[ 3, 11,  9, 15, 19, 17, 13]])

## 11

Crea una función llamada f que acepte como parámetro el número y que retorne lo siguiente:

*    Si es valor está en el rango ]-inf,3[ que retorne 0
*    Si es valor está en el rango [3,5[ que retorne 4
*    Si es valor está en el rango [5,6[ que retorne 5
*    Si es valor está en el rango [6,7[ que retorne 6
*    Si es valor está en el rango [7,9[ que retorne 8
*    Si es valor está en el rango [9,+inf[ que retorne 10

Crea ahora el vector de numpy [1,5,4,7,3,9,8,6] y aplícale la función f

In [279]:
def f(num):
    if num <3:
        return 0
    elif num < 5:
        return 4
    elif num < 6:
        return 5
    elif num < 7:
        return 6
    elif num < 9:
        return 8
    else:
        return 10

In [280]:
array11 = [1,5,4,7,3,9,8,6]

In [302]:
for n in array11:
    print(f(n),end=" ")
    

0 5 4 8 4 10 8 6 

## 12

Dado el siguiente array:

redes = [
        [4, 8, 4, 2, 1],
        [4, 8, 4, 2, 1],
        [8, 16, 8, 4, 1], 
        [8, 16, 8, 4, 1], 
        [16, 32, 16, 8, 1], 
        [16, 32, 16, 8, 1], 
        [32, 64, 32, 8, 1], 
        [32, 64, 32, 8, 1], 
        [64, 128, 64, 8, 1], 
        [64, 128, 64, 8, 1]
        ]

Calcula:
*    El Nº Máximo en cualquier red
*    El Nº máximo en cada red
*    El Nº máximo en cada capa
*    El Nº máximo en la 3º red
*    El Nº máximo en la 3º capa


In [282]:
redes = [[4, 8, 4, 2, 1], [4, 8, 4, 2, 1], [8, 16, 8, 4, 1], [8, 16, 8, 4, 1], [16, 32, 16, 8, 1], [16, 32, 16, 8, 1], [32, 64, 32, 8, 1], [32, 64, 32, 8, 1], [64, 128, 64, 8, 1], [64, 128, 64, 8, 1]]

print(np.max(redes))

128


In [283]:
i = 1
for red in redes:
    print("Red",i,"MAX -> ", end="")
    print(np.max(red))
    i+=1

Red 1 MAX -> 8
Red 2 MAX -> 8
Red 3 MAX -> 16
Red 4 MAX -> 16
Red 5 MAX -> 32
Red 6 MAX -> 32
Red 7 MAX -> 64
Red 8 MAX -> 64
Red 9 MAX -> 128
Red 10 MAX -> 128


In [284]:
i = 1
for mcap in np.max(redes, axis = 0):
    print("Capa",i,"MAX -> ", end="")
    print(mcap)
    i+=1

Capa 1 MAX -> 64
Capa 2 MAX -> 128
Capa 3 MAX -> 64
Capa 4 MAX -> 8
Capa 5 MAX -> 1


In [285]:
print("Max de la red 3 -> ",np.max(redes[2]))
print("Max de la capa 3 -> ",np.max(redes,axis=0)[2])

Max de la red 3 ->  16
Max de la capa 3 ->  64


## 13

Crea una función llamada mostrar_tamanyo que le pasemos un array de numpy y nos imprima el tamaño de cada una de las dimensiones.

<pre>
Por ejemplo con el array:
array([[[ 2,  3],
        [ 5,  7]],

       [[11, 13],
        [17, 19]],

       [[23, 29],
        [31, 37]]]) 
Deberá mostrar:
El nº de elementos de la dimension 0 es 3
El nº de elementos de la dimension 1 es 2
El nº de elementos de la dimension 2 es 2
</pre>

In [286]:
array13 = np.array([[[ 2,  3],
        [ 5,  7]],

       [[11, 13],
        [17, 19]],

       [[23, 29],
        [31, 37]]]) 
array13.shape

(3, 2, 2)

In [287]:
array13.ndim

3

In [288]:
def mostrar_tamanyo(arr):
    for i in range(arr.ndim):
        print(arr.shape[i])
        print("----")
mostrar_tamanyo(array13)

3
----
2
----
2
----


## 14

Crea la siguiente matriz:

<pre>
array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [10., 11., 12., 13., 14., 15.],
       [20., 21., 22., 23., 24., 25.],
       [30., 31., 32., 33., 34., 35.],
       [40., 41., 42., 43., 44., 45.],
       [50., 51., 52., 53., 54., 55.]])
</pre>

In [289]:
array14 = np.array([])
for i in range(0,60, 10):
    subarr =[]
    for j in range(0,6):
        subarr = np.append(subarr,(j+i))
    array14 = np.append(array14,subarr)
array14 = np.divide(array14,1).reshape(6,6)
array14

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [10., 11., 12., 13., 14., 15.],
       [20., 21., 22., 23., 24., 25.],
       [30., 31., 32., 33., 34., 35.],
       [40., 41., 42., 43., 44., 45.],
       [50., 51., 52., 53., 54., 55.]])

## 15

MUESTRA TODO LO QUE ESTÁ SELECCIONADO:
* NARANJA
* VERDE OSCURO (TURQUESA)
* ROJO
* VERDE CLARO

![Matriz](./matriz.png)

In [290]:
array14[0,[3,4]]


array([3., 4.])

In [291]:
array14[2::2,::2]

array([[20., 22., 24.],
       [40., 42., 44.]])

In [292]:
array14[:,2]

array([ 2., 12., 22., 32., 42., 52.])

In [293]:
print(array14[-2,[-2,-1]])
print(array14[-1,[-2,-1]])

[44. 45.]
[54. 55.]


## 16

MUESTRA TODO LO QUE ESTÁ SELECCIONADO:
* NARANJA
* AZUL
* ROJO

![Matriz](./matriz2.png)

In [294]:
for i in range(len(array14[0])):
    try:
        print(array14[i][i+1],end=" ")
    except:
        pass

1.0 12.0 23.0 34.0 45.0 

In [295]:
j = 0
for row in range(0,3):
    for i in range(0,3):
        print(array14[row+3][i+j],end=" ")


        j+=1+i
    j = 0
    print()
    j = 0

30.0 32.0 35.0 
40.0 42.0 45.0 
50.0 52.0 55.0 


In [296]:
for i in range(0,3):
    print(array14[i+j][2],end=" ")
    j+=1+i

2.0 22.0 52.0 

## 17

También se puede acceder a matrices multidimensionales utilizando secuencias enteras y matrices booleanas.

Supongamos que x es una matriz bidimensional e inds es el subíndice representado por el tipo de matriz de una secuencia entera:
* Si inds es una matriz unidimensional, x [inds] devuelve una matriz bidimensional, pero si inds es una matriz bidimensional, x [inds] devuelve una matriz tridimensional.

In [297]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
inds=np.array([[0,1,2,]])
print(x.shape)
x[inds].shape

(3, 3)


(1, 3, 3)

## 18

How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [298]:
array18 = np.array([1,2,3,4,5])


In [299]:
array18 = np.expand_dims(array18, 0)

In [300]:
array18.shape

(1, 5)