# Ejercicio resuelto del tema de Regresión

In [16]:
import pandas as pd
import numpy as np

In [17]:
# Importamos un dataset de los precios de las casas en Boston
from sklearn import datasets ## imports datasets from scikit-learn
data = datasets.load_boston() ## loads Boston dataset from datasets library

In [18]:
# define the data/predictors as the pre-set feature names  
df = pd.DataFrame(data.data, columns=data.feature_names)

# Put the target (housing value -- MEDV) in another DataFrame
target = pd.DataFrame(data.target, columns=["MEDV"])

In [19]:
'''Muestra las primeras filas del dataframe df y target'''
df.head(5)


CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0  0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1  0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2  0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3  0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4  0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33

[5 rows x 13 columns]

In [20]:
target.head(5)

MEDV
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

In [21]:
X = df.to_numpy()

In [22]:
y = target.to_numpy()

In [23]:
''' Crea un modelo de regresión lineal y entrénalo '''
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X, y)
''' Prueba a entrenarlo con df y target en lugar de X e y '''
model.fit(df, target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [24]:
''' Predice el precio de una vivienda con los siguintes datos
0.03731	0.0	7.07	0.0	0.469	6.421	23.5	4.9671	2.0	242.0	17.8	396.90 9.14
NOTA: se corresponde con la segunda vivienda, pero con la edad de 23.5 años en lugar de 78.9'''


' Predice el precio de una vivienda con los siguintes datos\n0.03731\t0.0\t7.07\t0.0\t0.469\t6.421\t23.5\t4.9671\t2.0\t242.0\t17.8\t396.90 9.14\nNOTA: se corresponde con la segunda vivienda, pero con la edad de 23.5 años en lugar de 78.9'

In [25]:
X_test = np.array([[0.02731,	0.0,	7.07,	0.0,	0.469,	6.421,	23.5,	4.9671,	2.0,	242.0,	17.8,	396.90, 9.14]])

In [26]:
X_test.shape

(1, 13)

In [27]:
model.predict(X_test)

array([[24.98721313]])

In [28]:
''' ¿Cuál es el coeficiente de determinación R2? y MSE?'''

from sklearn import metrics
y_pred = model.predict(X)
print('R2:', metrics.r2_score(y, y_pred))
print('MSE:', metrics.mean_squared_error(y, y_pred))

R2: 0.7406426641094095
MSE: 21.894831181729202


In [29]:
''' Muestra los coeficientes y el punto de corte (intercept) '''
model.coef_

array([[-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,
         2.68673382e+00, -1.77666112e+01,  3.80986521e+00,
         6.92224640e-04, -1.47556685e+00,  3.06049479e-01,
        -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
        -5.24758378e-01]])

In [30]:
model.intercept_

array([36.45948839])

# Vamos a comparar el resultado de realizar una regresión lineal sin normalización y con normalización

## 1. Primero sin normalizar

In [ ]:
''' Divide el dataset en entrenamiento y test. Usa el 30% para test.
Utiliza random_state para poder ejecutar varias veces y obtener los mismos datos aleatorios y poder comparar'''


In [ ]:
''' Crea el modelo de Regresión lineal y entrénalo con el conjunto de entrenamiento '''


In [ ]:
''' Calcula y_pred del conjunto de test '''


In [ ]:
''' Muestra los valores de R2 y MSE para el conjunto de test '''


## 2. Ahora normalizando

In [ ]:
''' Crea un escalador StandardScaler 
y aplícalo sobre X_train y X_test''' 


In [ ]:
''' Crea un modelo de Regresión lineal. Llámalo modelo2 y entrénalo con los datos normalizados '''



In [ ]:
''' calcula y_pred2 a partir de los datos de test normalizados '''


In [ ]:
''' Calcula las mátricas R2 y MSE y comprueba si ha habido mejora '''
