# Ejercicio resuelto del tema de Regresión

In [134]:
import pandas as pd
import numpy as np

In [135]:
# Importamos un dataset de los precios de las casas en Boston
from sklearn import datasets ## imports datasets from scikit-learn
data = datasets.load_boston() ## loads Boston dataset from datasets library

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [136]:
# define the data/predictors as the pre-set feature names  
df = pd.DataFrame(data.data, columns=data.feature_names)

# Put the target (housing value -- MEDV) in another DataFrame
target = pd.DataFrame(data.target, columns=["MEDV"])

In [137]:
'''Muestra las primeras filas del dataframe df y target'''
df.head(5)


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [138]:
target.head(5)

MEDV
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

In [139]:
X = df.to_numpy()

In [140]:
y = target.to_numpy()

In [141]:
''' Crea un modelo de regresión lineal y entrénalo '''
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X, y)
''' Prueba a entrenarlo con df y target en lugar de X e y '''
model.fit(df, target)

LinearRegression()

In [142]:
''' Predice el precio de una vivienda con los siguintes datos
0.03731	0.0	7.07	0.0	0.469	6.421	23.5	4.9671	2.0	242.0	17.8	396.90 9.14
NOTA: se corresponde con la segunda vivienda, pero con la edad de 23.5 años en lugar de 78.9'''


' Predice el precio de una vivienda con los siguintes datos\n0.03731\t0.0\t7.07\t0.0\t0.469\t6.421\t23.5\t4.9671\t2.0\t242.0\t17.8\t396.90 9.14\nNOTA: se corresponde con la segunda vivienda, pero con la edad de 23.5 años en lugar de 78.9'

In [143]:
X_test = np.array([[0.02731,	0.0,	7.07,	0.0,	0.469,	6.421,	23.5,	4.9671,	2.0,	242.0,	17.8,	396.90, 9.14]])

In [144]:
X_test.shape

(1, 13)

In [145]:
model.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([[24.98721313]])

In [146]:
''' ¿Cuál es el coeficiente de determinación R2? y MSE?'''

from sklearn import metrics
y_pred = model.predict(X)
print('R2:', metrics.r2_score(y, y_pred))
print('MSE:', metrics.mean_squared_error(y, y_pred))

R2: 0.7406426641094095
MSE: 21.894831181729202


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


In [147]:
''' Muestra los coeficientes y el punto de corte (intercept) '''
model.coef_

array([[-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,
         2.68673382e+00, -1.77666112e+01,  3.80986521e+00,
         6.92224640e-04, -1.47556685e+00,  3.06049479e-01,
        -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
        -5.24758378e-01]])

In [148]:
model.intercept_

array([36.45948839])

# Vamos a comparar el resultado de realizar una regresión lineal sin normalización y con normalización

## 1. Primero sin normalizar

In [149]:
''' Divide el dataset en entrenamiento y test. Usa el 30% para test.
Utiliza random_state para poder ejecutar varias veces y obtener los mismos datos aleatorios y poder comparar'''
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [150]:
''' Crea el modelo de Regresión lineal y entrénalo con el conjunto de entrenamiento '''

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)


LinearRegression()

In [151]:
''' Calcula y_pred del conjunto de test '''
y_pred = model.predict(X_test)

In [152]:
''' Muestra los valores de R2 y MSE para el conjunto de test '''
from sklearn.metrics import r2_score
print('R2:', metrics.r2_score(y_test, y_pred))
print('MSE:', metrics.mean_squared_error(y_test, y_pred))

R2: 0.7112260057484974
MSE: 21.517444231176903


## 2. Ahora normalizando

In [153]:
''' Crea un escalador StandardScaler 
y aplícalo sobre X_train y X_test''' 

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_std = sc.fit_transform(X_train)
X_test_std = sc.transform(X_test)

In [154]:
''' Crea un modelo de Regresión lineal. Llámalo modelo2 y entrénalo con los datos normalizados '''
modelo2 = LinearRegression()
modelo2.fit(X_train_std, y_train)


LinearRegression()

In [155]:
''' calcula y_pred2 a partir de los datos de test normalizados '''
y_pred2 = modelo2.predict(X_test_std)

In [156]:
''' Calcula las mátricas R2 y MSE y comprueba si ha habido mejora '''
print('R2:', metrics.r2_score(y_test, y_pred2))
print('MSE:', metrics.mean_squared_error(y_test, y_pred2))

R2: 0.7112260057484932
MSE: 21.51744423117721


In [157]:
''' Prueba con Ridge en lugar de LinearRegression '''
from sklearn.linear_model import Ridge
modelo3 = Ridge()
modelo3.fit(X_train, y_train)

Ridge()

In [158]:
y_pred3 = modelo3.predict(X_train)